spring:
  
      jpa:
          hibernate:
            ddl-auto: validate
          properties:
            hibernate.enable_lazy_load_no_trans: true
            hibernate:
              show_sql: true
              use_sql_comments: true
              format_sql: true
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect

      datasource:
           url: jdbc:mysql://localhost:3306/insertion_javatos_test
           username: root
           password:
           

