spring:
  
      jpa:
          hibernate:
            ddl-auto: validate
          properties:
            hibernate:
              show_sql: true
              use_sql_comments: true
              format_sql: true
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect

      datasource:
           url: jdbc:mysql://localhost:3306/insertion_test_javatosbdd
           username: root
           password:
           

